matrix:
  include:
    - language: java
      jdk: oraclejdk11
      before_script:
        - cd back
      script:
        - mvn -Dmaven.test.failure.ignore=true -B verify
    - language: node_js
      before_script:
        - cd web
      script:
        - npm ci